= Rehost

== Migrate the applications from Red Hat Virtualization to OpenShift Virtualization

The steps you will follow to migrate the *customers* service from Red Hat Enterprise Virtualization (RHV) to Red Hat OpenShift are as follows:

* Migrate the *Oracle VM* from RHV to OpenShift Virtualization using the OpenShift Migration Toolkit for Virtualization
* Modernize the Java source code for the *customers* application
* Use the https://tekton.dev/[Tekton^] Pipeline to build and deploy the new, modernized application using Red Hat Web Server instead of Apache Tomcat as the runtime.
* Set up the configuration for the *customers* service to connect to the Oracle database VM which is now running on OpenShift Container Platform
* Test the *customers* service
* Update the configuration for the *gateway* service to now point to the modernized *customers* service.
* Demonstrate that your *frontend* service still works as before.

=== Migrate the Oracle VM from RHV to OpenShift

==== Prerequisites

. Download the CA Certificate for your RHV environment. You need to do that on your laptop because you will need to drag the file into the MTV console later.
+
[source,sh]
----
# Set this variable to the RHV hostname from the e-mail
export RHV_HOST=<RHV_HOSTNAME>

wget -O $HOME/pki-resource.cer --no-check-certificate "https://${RHV_HOSTNAME}/ovirt-engine/services/pki-resource?resource=ca-certificate&format=X509-PEM-CA"
----

. Or if you prefer the web browser:
.. Navigate to `https://<RHV_HOSTNAME>/ovirt-engine/services/pki-resource?resource=ca-certificate&format=X509-PEM-CA` in your web browser (replace *<RHV_HOSTNAME>* with the hostname from your welcome e-mail - e.g. `rhvm.dev.cnv.infra.opentlc.com`).
.. On most systems this will download a file `pki-resource.cer` into your `Downloads` folder.
.. Take a note where this file got downloaded to. You will need it a little bit later.

=== Set up Virtualization Provider in MTV

. Log into the OpenShift Web Console using the URL and *admin* credentials provided
. On the left click on *Virtualization* -> *Virtual Machines*
. From the *Projects* drop down select the *retail* project.
.. There are no Virtual Machines yet.
. Click *Launch Migration Tool* to launch the OpenShift Migration Toolkit for Virtualization.
. Log in using your *admin* credentials
.. If this is the first time you are logging in click the blue *Get started* button.
. On the list of *Providers* click *Add provider*
. Select *Red Hat Virtualization* from the list of providers. Fill in the information from your e-mail:
.. *Name*: `RHV`
.. *RHV Manager host name or IP address*: The hostname from your e-mail. For example `rhvm.dev.cnv.infra.opentlc.com`
.. *RHV Manager user name*: the username from your e-mail. For example `migrateuser-wkama@internal`
.. *RHV Manager passsword*: the password from yoru e-mail. For example `niIEPihdCR7I`
.. *CA Certificate*: Drop the previously downloaded CA Certificate File
.. Click *Add*.
. MTV will validate your provider and after a few seconds the status should switch to *Ready*.

=== Create and execute Migration Plan

. In the *Migration Toolkit for Virtualization* console navigate to *Migration Plans*.
. Click *Create Plan*
. On the *General* page use the following parameters:
.. *Plan name*: `customers-database`
.. *Source provider*: select the *RHV* source provider you previously created
.. *Target provider*: select *host* (the OpenShift cluster you are currently on)
.. *Target namespace*: select *retail*
. Click *Next*
. On the *VM Selection / Filter* page select the checkbox next to *All datacenters*
. Click *Next*
. On the *VM Selection / Select VMs* page select the VM that got created for you. You will find the name in your welcome e-mail (future). The name will be something like *oracle-XXXXX* where XXXXX is your GUID.
. Click *Next*
. On the *Network Mapping* page click on *Select a network mapping* and select *Create a network mapping*.
. Leave the defaults and click *Next*
. On the *Storage Mapping* page click on *Select a storage mapping* and select *Create a storage mapping*.
. Change the *Target Storage Class* to `gp2-csi` and click *Next*
. On the *Type* page select *Cold migration* and click *Next*
// . On the *Type* page select *Warm migration* and click *Next*
. On the *Hooks* page click *Next*
. On the *Review* page click *Finish*

Now your Migration Plan is ready to use.

// WKTBD: figure out correct permissions for Warm Migration to work....
// The migration will happen in two stages. First a snapshot of the current state of the disk in RHV is copied to OpenShift. The database VM can keep running in RHV during that stage not disrupting our running application.

// Once the *incremental data copy* step has finished you can then execute the cutover from RHV to OpenShift Virtualization.

To execute the plan click the *Start* button next to your *customers-database* migration plan and confirm by clicking the blue *Start* button in the popup window.

Because you are running a *cold migration* the VM in RHV gets shutdown first.

The migration will take about 15-25 minutes after which you will have a running Oracle database VM in your OpenShift cluster.

Once the migration succeeds you will find a VM called `oracle-xxxxx` in your retail namespace.

=== Post Migration Tasks:

The VM is not yet reachable from other applications on the cluster. You will need to add a label to the VM and then create a service to be able to connect to the database on the VM.

. Add a label to your VM's template metadata (make sure to replace `wkama` with your GUID).
+
[source,sh]
----
oc patch vm oracle-wkama --type=merge --patch='{"spec": { "template": { "metadata": { "labels": { "app": "oracle-wkama"}}}}}' -n retail
----

. Restart the VM for the VM Pod to pick up the new label.
+
You can restart the VM either from the OpenShift Web Console or using `virtctl` from the bastion VM.

.. Navigate to your VM in the OpenShift Web Console:
... *Virtualization* -> *VirtualMachines*
... Click on your VM
... From the *Action* drop down select *Restart* then confirm by clicking *Restart* in the pop up dialog.
.. Or use `virtctl` to restart the VM:
+
[source,sh]
----
virtctl restart oracle-${GUID} -n retail
----

. Create service for database vm:
+
[source,sh]
----
oc create service clusterip oracle-${GUID} --tcp=1521:1521 --tcp=2022:22 -n retail
----

. Make sure your service has the endpoint for the Oracle VM pod as an Endpoint:
+
[source,sh]
----
oc describe svc oracle-${GUID} -n retail
----
+
.Sample Output
[source,texinfo]
----
Name:              oracle-wkama
Namespace:         retail
Labels:            app=oracle-wkama
Annotations:       <none>
Selector:          app=oracle-wkama
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                172.30.4.130
IPs:               172.30.4.130
Port:              1521-1521  1521/TCP
TargetPort:        1521/TCP
Endpoints:         10.128.1.14:1521
Port:              2022-22  2022/TCP
TargetPort:        22/TCP
Endpoints:         10.128.1.14:22
Session Affinity:  None
Events:            <none>
----

➡️ Next section: link:./6-deploy-to-kubernetes.adoc[6 - Deploy to Kubernetes]